 
version: "3.4"

services:
  server:
    restart: always
    build:
      context: ./
      dockerfile: win.Dockerfile
    image: "rpclib:latest"
    command: ["/usr/local/bin/server"]
  client:
    restart: always
    build:
      context: ./
      dockerfile: nix.Dockerfile    
    depends_on:
      - server
    image: "rpclib:latest"
    command: ["/usr/local/bin/client"]