 
version: "3.4"

services:
  server:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    image: "rpclib:latest"
    command: ["/usr/local/bin/server"]
  client:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile    
    depends_on:
      - server
    image: "rpclib:latest"
    command: ["/usr/local/bin/client"]